spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/VTBShop
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db_log/db-changelog-master.yaml
    enabled: true